// JWT_SECRET = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjEzZTA5MDZhZmZiY2Q2YTc4NjZiNWYiLCJpYXQiOjE3MTI1OTk2MTl9.DyiJPjHbPvbyZezL-2l_9eI4BVvRPZ18qKPc3Kr1lu8"
module.exports = {
    MONGOURI:process.env.MONGOURI
}